version: '3.8'

services:
  mongodb-tareas:
    image: mongo:latest
    container_name: mongodb-tareas
    ports:
      - '27019:27019'
    volumes:
      - mongo-data:/data/db

  tareas-service:
    build: .
    container_name: tareas-service
    ports:
      - '3001:3001'
    environment:
      - MONGODB_URI=mongodb://mongodb-tareas:27019/tareas
    depends_on:
      - mongodb-tareas

volumes:
  mongo-data:
