version: '3.8'

services:
  project-service:
    build:
      context: ./app
    ports:
      - "5003:5003"
    depends_on:
      - postgres-project
    env_file:
      - .env

  postgres-project:
    build:
      context: ./db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
