version: '3.8'

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    build: ./db
    volumes:
      - sqlite_data:/db

volumes:
  sqlite_data: