version: '3.8'

services:
  auth-service:
    build: ./backend/auth-service
    ports:
      - "${AUTH_PORT}:5001"
    depends_on:
      - mongo-auth

  mongo-auth:
    image: mongo:latest
    ports:
      - "${MONGO_AUTH_PORT}:27018"
    volumes:
      - mongo-data2:/data/db

  finance-services:
    build: ./backend/finance-services
    volumes:
      - ./backend/finance-services:/app
    ports:
      - "${FINANCE_PORT}:5002"
    env_file:
      - ./backend/finance-services/.env
    depends_on:
      - mysql-finance

  mysql-finance:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/finance-services/init.sql:/docker-entrypoint-initdb.d/init.sql

  mysqlFinance-exporter:
    image: prom/mysqld-exporter
    environment:
      - DATA_SOURCE_NAME=${MYSQL_USER}:${MYSQL_PASSWORD}@tcp(mysql-finance:3306)
    ports:
      - "9104:9104"

  project-service:
    build:
      context: ./backend/project-service/app
    ports:
      - "${PROJECT_PORT}:5003"
    depends_on:
      - postgres-project
    env_file:
      - ./backend/project-service/.env

  postgres-project:
    build:
      context: ./backend/project-service/db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    environment:
      - DATA_SOURCE_NAME=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres-project:5433/${POSTGRES_DB}
    ports:
      - "9187:9187"

  reports-service:
    build: ./backend/reports-service
    ports:
      - "${REPORTS_PORT}:5004"
    environment:
      - PYTHONUNBUFFERED=1

  socios-service:
    build: ./backend/socios-service
    volumes:
      - ./backend/socios-service/db:/db
    ports:
      - "${SOCIOS_PORT}:3000"

  mongodb-tareas:
    image: mongo:latest
    container_name: mongodb-tareas
    ports:
      - "${MONGO_TAREAS_PORT}:27019"
    volumes:
      - mongo-data1:/data/db

  tareas-service:
    build: ./backend/tareas-service
    container_name: tareas-service
    ports:
      - "${TAREAS_PORT}:3001"
    environment:
      - MONGODB_URI=mongodb://mongodb-tareas:27019/tareas
    depends_on:
      - mongodb-tareas

  mongodbTareas-exporter:
    image: percona/mongodb_exporter:0.40
    environment:
      - MONGODB_URI=mongodb://mongodb-tareas:27019
    ports:
      - "9216:9216"

  mongodbAuth-exporter:
    image: percona/mongodb_exporter:0.40
    environment:
      - MONGODB_URI=mongodb://mongo-auth:27018/authdb
    ports:
      - "9218:9218"

  votacio-service:
    build: ./backend/votacio-service
    ports:
      - "${VOTACIO_PORT}:5005"
    environment:
      - FLASK_APP=${FLASK_APP}
      - FLASK_ENV=${FLASK_ENV}
    depends_on:
      - mariadb-votacio

  mariadb-votacio:
    build:
      context: ./backend/votacio-service
      dockerfile: Dockerfile.db
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

  mysqlVotacio-exporter:
    image: prom/mysqld-exporter
    environment:
      - DATA_SOURCE_NAME=${MYSQL_USER}:${MYSQL_PASSWORD}@tcp(mariadb-votacio:3306)/${MYSQL_DATABASE}
    ports:
      - "9105:9105"


  prometheus:
    image: prom/prometheus:v2.44.0
    volumes:
       - ./backend/monitoring-service/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    ports:
      - "9000:9000"
    depends_on:
      - prometheus

volumes:
  mongo-data1:
  mongo-data2:
  mysql_data:
  postgres_data:
  sqlite_data:
  db_data:
