global:
  resolve_timeout: 5m

route:
  receiver: 'default'
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h

receivers:
  - name: 'default'
    email_configs:
      - to: 'a3youb@gmail.com'
        from: 'a3youb@gmail.com'
        smarthost: 'smtp.freesmtpservers.com:25'
       

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
