# Dockerfile for the database service
FROM mariadb:latest

COPY init.sql /docker-entrypoint-initdb.d/

# Ejecutar el script init.sql al iniciar el contenedor
#CMD ["bash", " sleep 10 && mariadb -u ${MYSQL_USER} -p${MYSQL_PASSWORD} ${MYSQL_DATABASE} < /docker-entrypoint-initdb.d/init.sql"]