{
 "title": "Comunitat",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Finance-Services",
   "type": "timeseries",
   "description": "Gestio de despeses i Ingress",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "scrape_duration_seconds{job=\"microservices\", instance=\"finance-services:5002\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Auth-Service",
   "type": "timeseries",
   "description": "Servei de Autentificació",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "scrape_duration_seconds{job=\"microservices\", instance=\"auth-service:5001\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Project-Service",
   "type": "timeseries",
   "description": "Gestio de Projectes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "scrape_duration_seconds{job=\"microservices\", instance=\"project-service:5003\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reports-Service",
   "type": "timeseries",
   "description": "Gestio de Reportes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "scrape_duration_seconds{job=\"microservices\", instance=\"reports-service:5004\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Socios-Service",
   "type": "timeseries",
   "description": "Gestio de socis",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "scrape_duration_seconds{job=\"microservices\", instance=\"socios-service:3000\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tareas-Service",
   "type": "timeseries",
   "description": "Gestio de tareas",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "scrape_duration_seconds{job=\"microservices\", instance=\"tareas-service:3001\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Votacio-Service",
   "type": "timeseries",
   "description": "Gestio de Votacions i feedback",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "scrape_duration_seconds{job=\"microservices\", instance=\"votacio-service:5005\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "http_requests_total{job=\"microservices\", instance=\"auth-service:5001\"}"
    }
   ]
  }
 ]
}