version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  app:
    build: .
    container_name: tareas
    ports:
      - '3001:3001'
    environment:
      - MONGODB_URI=mongodb://mongo:27017/tareas
    depends_on:
      - mongo

volumes:
  mongo-data:
