global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'microservices'
    static_configs:
      - targets: ['microservice1:8080', 'microservice2:8080', 'microservice3:8080']