version: '3.8'

services:
  app:
    build:
      context: ./app
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env

  db:
    build:
      context: ./db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
