version: '3.8'

services:
  finance-services:
    build: .
    volumes:
      - .:/app
    ports:
      - "5002:5002"
    env_file:
      - .env
    depends_on:
      - mysql-finance

  mysql-finance:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data:
