FROM python:3.9-slim

WORKDIR /app

# Install necessary system packages
RUN apt-get update && apt-get install -y pkg-config libmariadb-dev build-essential

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY . .

CMD ["python", "app/routes.py"]
