version: '3.8'

services:
  auth-service:
    build: .
    ports:
      - "5001:5001"
    environment:
      - MONGODB_URI=mongodb://mongo-auth:27018/authdb
    depends_on:
      - mongo-auth
    env_file:
      - .env

  mongo-auth:
    image: mongo:latest
    ports:
      - "27018:27018"
    volumes:
      - mongo-data:/data/db
  

volumes:
  mongo-data:

  